<?php

declare(strict_types=1);

use App\Models\User;
use Tests\TestCase;
use \Illuminate\Foundation\Testing\RefreshDatabase;

class PaginatorTest extends TestCase
{
    use RefreshDatabase;



    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        User::factory()->count(100)->create();
    }

    /**
     * @test
     */
    public function it_can_paginate_test(): void
    {

        dump(count(User::all()));

        //appends
        $users = User::paginate(10)->appends(['sort' => 'name']);
        $users = User::paginate(10)->appends(['id' => 1]);
        $users = User::paginate(10);
        // \Illuminate\Database\Eloquent\Builder::
        // \Illuminate\Pagination\LengthAwarePaginator::

        dump($users->pluck('name', 'id')->toArray());
        exit;
        $users = User::paginate(10);


        dump($users->currentPage());
        dump($users->total());
        // dump($users);
    }

    /**
     * @test
     * @return void
     */
    public function it_can_simple_paginate(): void
    {
        $users = User::simplePaginate(15);

    }
}
